version: 1.0.{build}

branches:
  only:
    - master

skip_commits:
  files:
  - LICENCE
  - '**/*.md'

configuration: Release

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
  - nuget restore

build:
  project: Owin.SelfHost.Runner.sln
  publish_nuget: true
  include_nuget_references: true
  verbosity: normal

artifacts:
- path: Owin.SelfHost.Runner\bin\$(configuration)
  name: Owin.SelfHost.Runner

deploy:
- provider: NuGet
  api_key:
    secure: JEds1HdkxoPyf8p79f8FRU/ysyma6yMLi1sMFbjoJxHjMRJRTXTurWcHtfVyqD8V
  artifact: /.*\.nupkg/
